#![find a way to substitute home dir]/bin/last-commit/env/bin/python

import datetime
import arrow
from pathlib import Path, PurePath
import os.path

filename = str(PurePath(os.path.expanduser("~"), Path(".last-git-commit")))
if not Path(filename).is_file():
    print("NA")
    exit()


with open(filename, 'r') as f:
    last_commit_string = f.read().strip()
    print(arrow.get(last_commit_string).humanize())

